### PR TITLE
fixes issue #222 clear walk path after attack request

### LINKED ISSUE #222: Attacking after clicking to walk doesn't stop the walk
The walk path should be cleared if an attack is attempted after clicking to walk

### PR DESCRIPTION
**Pull request by CoderDanUK**
https://user-images.githubusercontent.com/464887/206895631-fbe531c1-f24b-4a7b-894c-e560067c7239.mp4

Fixes #222

### CODE REVIEW

File: EndlessClient/Rendering/Character/CharacterAnimator.cs [hunk 1]
```diff
@@ -432,6 +431,11 @@ private CharacterRenderProperties FaceTarget(MapCoordinate characterCoord, MapCo
             return rp;
         }
 
+        public void ClearWalkPath()
+        {
+            _walkPath.Clear();
```
Comment (ethanmoffat) [inline EndlessClient/Rendering/Character/CharacterAnimator.cs:436]: Instead of exposing details of `_walkPath` outside of `CharacterAnimator`, how about clearing the walk path in the `Attack` call of `CharacterAnimator`? Is there a reason that wouldn't work that I'm not thinking of?

Comment (CoderDanUK) [reply EndlessClient/Rendering/Character/CharacterAnimator.cs:436]: I think you're right I'll have a look into this 😊
